name: 'Create a release pull-request'
description: 'Create a release pull-request.'
author: 'grassedge'
inputs:
  owner:
    description: "Default is current reopsitory's owner."
  repo:
    description: "Default is current reopsitory's name."
  base:
    required: true
  head:
    required: true
  assign:
    description: "If true, assign each pull-req's assignees to the release pull-req"
  labels:
    description: 'Labels that is added to the release pull-request'
  template:
    description: 'Path to the template you want to use.'
  token:
    description: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'image'
  color: 'gray-dark'
